set ruler 
set autoindent
set smartindent
set laststatus=2
set showcmd
set hlsearch
set ignorecase
set smartcase
set confirm
set visualbell
set t_vb=
set cmdheight=2
set textwidth=120
"set foldmethod=indent

highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%' . (&textwidth + 1) . 'v', 100)


set spelllang=en,de
" set spell

" set UI language to english
set langmenu=en_US
let $LANG='en_US'
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim

" alias some commands I type incorrectly
command Q q
command W w
command Wq wq
command WQ wq


call plug#begin('~/.vim/plugged')

    Plug 'valloric/youcompleteme'
    Plug 'skywind3000/asyncrun.vim'
    Plug 'embear/vim-localvimrc'
	Plug 'scrooloose/nerdtree'
    Plug 'sheerun/vim-polyglot'
    Plug 'Yggdroot/indentLine'
    Plug 'frazrepo/vim-rainbow'
    
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'

    Plug 'sirver/ultisnips'
    Plug 'jpalardy/vim-slime'

call plug#end()

filetype plugin on
syntax on
set omnifunc=syntaxcomplete#Complete

let NERDTreeIgnore = ['\.aux$']

" set airline theme
let g:airline_solarized_bg='dark'

" activate rainbow brackets for every file type
let g:rainbow_active = 1

" remove security feautures of localvimrc
let g:localvimrc_sandbox = 0
let g:localvimrc_ask = 0

let g:ycm_autoclose_preview_window_after_completion = 1

" set vim slime to tmux
let g:slime_target = "tmux"

" ## added by OPAM user-setup for vim / base ## 93ee63e278bdfc07d1139a748ed3fff2 ## you can edit, but keep this line
let s:opam_share_dir = system("opam config var share")
let s:opam_share_dir = substitute(s:opam_share_dir, '[\r\n]*$', '', '')

let s:opam_configuration = {}

function! OpamConfOcpIndent()
  execute "set rtp^=" . s:opam_share_dir . "/ocp-indent/vim"
endfunction
let s:opam_configuration['ocp-indent'] = function('OpamConfOcpIndent')

function! OpamConfOcpIndex()
  execute "set rtp+=" . s:opam_share_dir . "/ocp-index/vim"
endfunction
let s:opam_configuration['ocp-index'] = function('OpamConfOcpIndex')

function! OpamConfMerlin()
  let l:dir = s:opam_share_dir . "/merlin/vim"
  execute "set rtp+=" . l:dir
endfunction
let s:opam_configuration['merlin'] = function('OpamConfMerlin')

let s:opam_packages = ["ocp-indent", "ocp-index", "merlin"]
let s:opam_check_cmdline = ["opam list --installed --short --safe --color=never"] + s:opam_packages
let s:opam_available_tools = split(system(join(s:opam_check_cmdline)))
for tool in s:opam_packages
  " Respect package order (merlin should be after ocp-index)
  if count(s:opam_available_tools, tool) > 0
    call s:opam_configuration[tool]()
  endif
endfor
" ## end of OPAM user-setup addition for vim / base ## keep this line
" ## added by OPAM user-setup for vim / ocp-indent ## 08f3df7dfcf33f1b86603021f70f1176 ## you can edit, but keep this line
if count(s:opam_available_tools,"ocp-indent") == 0
  source "/Users/tom/.opam/4.11.0/share/ocp-indent/vim/indent/ocaml.vim"
endif
" ## end of OPAM user-setup addition for vim / ocp-indent ## keep this line
